version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: global_snack
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"

#  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql
#      - maildev
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/global_snack
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=1234