mailServer:
  host: smtp.gmail.com
  port: 587
  email: haikvph14059@fpt.edu.vn
  password: jjqi fskh hcho pzcn
  protocol: smtp
  isSSL: false

frontend:
  base-endpoint: https://vnk25.store

backend:
  base-endpoint: https://vnk-backend-application.azuremicroservices.io